export const LOGIN_USER = 'LOGIN_USER';

export const OPEN_POPUP = 'OPEN_POPUP';
export const CLOSE_POPUP = 'CLOSE_POPUP';
export const LOADING_POPUP = 'LOADING_POPUP';
export const LOADED_POPUP = 'LOADED_POPUP';
export const SET_ERROR_POPUP = 'SET_ERROR_POPUP';
export const CLEAR_ERROR_POPUP = 'CLEAR_ERROR_POPUP';

export const UPDATE_WORKFLOWS = 'UPDATE_WORKFLOWS';

export const CLEAR_STATE = 'CLEAR_STATE';
